Repository knative/community, pull requests merged in 2019-05, with the labels that each got.

#1 add missing frontmatter to enable site build
  REPOSITORY-GUIDELINES.md
Labels: approved, lgtm

#4 Adding operations WG
  WORKING-GROUPS.md
Labels: approved, lgtm, size/S

#6 Elaborate on how to raise issues to the steering committee
  STEERING-COMMITTEE.md
Labels: approved, lgtm, size/S

#5 Add Dan as a lead for the Serving API Working Group
  WORKING-GROUPS.md
Labels: approved, lgtm, size/XS
