Repository knative/community, pull requests merged in 2019-11, with the labels that each got.

#41 Fix link to ROLES
  mechanics/WORKING-GROUP-PROCESSES.md
Labels: approved, lgtm, size/XS

#38 Remove build references in community repo
  DOCS-CONTRIBUTING.md
  README.md
  WORKING-GROUPS.md
Labels: approved, lgtm, size/S

#43 Adding sources charter.
  TECH-OVERSIGHT-COMMITTEE.md
  WORKING-GROUPS.md
Labels: approved, lgtm, size/M
