Repository knative/community, pull requests merged in 2020-07, with the labels that each got.

#172 Add Cris Zong to the Knative org
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#175 Add nthnca to the members list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#155 Update working group processes to match actual behavior.
  mechanics/WORKING-GROUP-PROCESSES.md
Labels: approved, cla: yes, lgtm, size/M

#170 Add discovery repo to peribolos
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#173 updating to the new schedule
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm

#176 Add arenault to knative member list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#180 Reflect the net-http01 migration in Peribolos
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#181 Fix the peribolos configuration file for knative-sandbox
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#178 add LICENSE file
  LICENSE
Labels: approved, cla: yes, lgtm, size/XL

#154 Fix links in WORKING-GROUPS.md
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#177 Add Ashleigh as Docs WG lead
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#182 Move net-{certmanager,contour} to knative-sandbox.
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#184 Add config missing from https://github.com/knative/community/pull/182
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#185 Remove urasoko from peribolos config file to get rid of the job error
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#189 Move remaining net-* repos to knative-sandbox.
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/M

#190 update company information
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#192 add new steering members to peribolos
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#196 Add zhongduo to members list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#197 Add danyinggu to the member list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#198 Remove urasoko from the configuration file to fix the Knative peribolos Prow job
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#125 Add docs on creating sandbox repos
  .github/ISSUE_TEMPLATE/new-repo.md
  .github/ISSUE_TEMPLATE/process.md
  .github/ISSUE_TEMPLATE/question.md
  mechanics/CREATING-A-SANDBOX-REPO.md
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/L

#201 Add cr22rc to members list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
