Repository knative/community, pull requests merged in 2020-08, with the labels that each got.

#204 Clarify the K8s minimum version principle
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: approved, cla: yes, lgtm, size/XS

#208 Added myself to eventing triage
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#207 Retire the Observability Working Group
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/M

#209 Add permissions for Knative Release Leads
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#200 Document the process to sunset a feature from Knative.
  mechanics/SUNSETTING-FEATURES.md
Labels: approved, cla: yes, lgtm, size/M

#215 Fix location of steering committee issues
  STEERING-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/XS

#219 Add a .github repo to sandbox
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/S

#220 adding myself to Eventing Triage
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#227 True up community with serving#9057, serving #9058, and mdemirhan stepping down
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/S

#231 Advertise @serving-help and @eventing-help Slack user group.
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#226 Document release schedule for the next 9 months
  mechanics/RELEASE-SCHEDULE.md
Labels: approved, cla: yes, lgtm, size/S

#240 Add wg-repository template for new repos
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#244 Add myself into member list
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#242 Git Hub Action - downstream-test-go
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#246 add async repo to peribolos knative-sandbox.yaml
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#247 add myself as member
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS
