Repository knative/community, pull requests merged in 2020-01, with the labels that each got.

#52 Format footnotes to be more obviously footnotes.
  mechanics/FEATURE-TRACKS.md
Labels: approved, lgtm, size/S

#55 Remove unused roles
  ROLES.md
Labels: approved, lgtm, size/M

#54 Add new VALUES.md for project values
  TEAM-VALUES.md
  VALUES.md
Labels: approved, lgtm, size/L

#56 Add / update roles
  ROLES.md
Labels: approved, lgtm, size/L

#61 Update Evan's employer on TOC page
  TECH-OVERSIGHT-COMMITTEE.md
Labels: approved, lgtm, size/XS

#63 update web conf link for api-core
  WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#57 Update Google steering members
  STEERING-COMMITTEE.md
Labels: approved, lgtm, size/XS

#62 Fix casing of VMware
  TECH-OVERSIGHT-COMMITTEE.md
Labels: approved, lgtm, size/XS

#65 Change meeting ID to fix recording problem.
  WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#66 Point to the meeting minutes for the VC link
  TECH-OVERSIGHT-COMMITTEE.md
Labels: approved, lgtm, size/XS

#67 Add rhuss as WG lead for client
  WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#64 Create docs folder
  OWNERS_ALIASES
  README.md
  docs/DOCS-CONTRIBUTING.md
  docs/OWNERS
  docs/README.md
  docs/_index.md
  docs/new-page-template.md
Labels: approved, lgtm, size/L

#45 Fix links, titles, frontmatter, and use fully qualified knative/docs URLs
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  README.md
  REPOSITORY-GUIDELINES.md
  REVIEWING.md
  ROLES.md
  SLACK-GUIDELINES.md
  STEERING-COMMITTEE.md
  TEAM-VALUES.md
  TECH-OVERSIGHT-COMMITTEE.md
  VALUES.md
  WORKING-GROUPS.md
  docs/DOCS-CONTRIBUTING.md
  docs/README.md
  docs/new-page-template.md
  mechanics/FEATURE-TRACKS.md
  mechanics/README.md
  mechanics/WORKING-GROUP-PROCESSES.md
  mechanics/_index.md
Labels: approved, lgtm, size/L

#74 fix table
  TECH-OVERSIGHT-COMMITTEE.md
Labels: approved, lgtm, size/XS

#75 Update leads for Productivity WG
  WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#77 Adds 2019 Knative Annual Report
  annual_reports/Knative 2019 Annual Report.pdf
Labels: approved, lgtm, size/XS
