Repository knative/community, pull requests merged in 2020-10, with the labels that each got.

#307 Initial work on gdocs migration tool with tcnghia.
  mechanics/tools/gdocs-migrate/.gitignore
  mechanics/tools/gdocs-migrate/README.md
  mechanics/tools/gdocs-migrate/go.mod
  mechanics/tools/gdocs-migrate/go.sum
  mechanics/tools/gdocs-migrate/main.go
  mechanics/tools/gdocs-migrate/oauth.go
Labels: approved, cla: yes, lgtm, size/XL

#306 Add Scott to Productivity Leads
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/L

#310 Adds VMware representative for trademark committee
  TRADEMARK-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/S

#315 Remove from milestone maintainers people who left project
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#313 Add tayarani to knative
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#312 adding scott to milestone maintainers
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#317 Add Navid as a Client WG Technical Lead
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#318 Add tayarani to sandbox
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#319 Removed bogus newline in working-groups.md
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#316 Add Ahmed Abdalla as Eventing WG execution lead
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/S

#321 Fix release schedule's year
  mechanics/RELEASE-SCHEDULE.md
Labels: approved, cla: yes, lgtm, size/S

#326 Add Doug Davis to KTC
  TRADEMARK-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/XS

#327 add yuvalif to members
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#328 add runzexia to knative/knative-sandbox members
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#329 Fix token caching bugs and add clarifying comments
  mechanics/tools/gdocs-migrate/main.go
  mechanics/tools/gdocs-migrate/oauth.go
Labels: approved, cla: yes, lgtm, size/M

#320 add kn-diag repo into peribolos/knative-sandbox.yaml
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#331 Create a repository to home the knobots.
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#332 Load all files metadata into a forest
  mechanics/tools/gdocs-migrate/forest.go
  mechanics/tools/gdocs-migrate/main.go
Labels: approved, cla: yes, lgtm, size/L

#342 create trademark group
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#341 Add quentin-cha to knative member list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#323 Create the hack repo
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#338 fix the Productivity wg meeting time
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/M

#339 Add almost complete election documentation for 2020 SC
  elections/2020/SC/README.md
  elections/2020/SC/candidate-template.md
  elections/2020/SC/voters.md
  elections/2020/TOC/README.md
  elections/2020/TOC/voters.md
  elections/README.md
  mechanics/SC.md
  mechanics/TOC.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#343 Added election officers to 2020 SC voting docs
  elections/2020/SC/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#334 Update the new-repo instructions
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: approved, cla: yes, lgtm, size/XS

#344 Sc 2020 election -- fix broken links
  elections/2020/SC/README.md
  elections/2020/TOC/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#345 Push one more 1 week for end of year holidays
  mechanics/RELEASE-SCHEDULE.md
Labels: approved, cla: yes, lgtm, size/S

#340 Add knative-automation to knative and knative-sandbox
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#336 Add kn-plugin-source-kafka to the peribolos sandbox config
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#349 Correct the Docs WG meeting time
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS
