Repository knative/community, pull requests merged in 2020-03, with the labels that each got.

#104 Add note about interim role removal
  ROLES.md
Labels: approved, lgtm, size/XS

#107 Update Operations WG meeting time and cal link
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/S

#108 k4leung4 steps down as Operations WG lead
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#109 Update meeting schedule for client WG
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS
