Repository knative/community, pull requests merged in 2020-11, with the labels that each got.

#353 Add mohamedelhawaty to knative member list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#352 add yuvalif to sandbox
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#354 Adding myself to the knative members list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#351 some clarifications/improvements as I test new repo checklist while adding new repos to knative-sandbox
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: approved, cla: yes, lgtm, size/XS

#356 Add Jacques Chester as SC candidate
  elections/2020/SC/jacques-chester.md
Labels: approved, cla: yes, lgtm, size/S

#359 Add pmorie to steering election 2020
  elections/2020/SC/pmorie.md
Labels: approved, cla: yes, lgtm, size/S

#362 Add Arghya Sadhu as SC election 2020 candidate
  elections/2020/SC/arghya-sadhu.md
Labels: approved, cla: yes, lgtm, size/S

#361 Add Carlos Santana 🎸 as SC election 2020 candidate
  elections/2020/SC/csantanapr.md
Labels: approved, cla: yes, lgtm, size/S

#363 goasguen SC candidacy
  elections/2020/SC/goasguen.md
Labels: approved, cla: yes, lgtm, size/S

#333 Add stuart-xyz to members list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#367 vaikas 2020 SC nomination
  elections/2020/SC/vaikas.md
Labels: approved, cla: yes, lgtm, size/M

#366 Add frontmatter so this page shows in the website too
  mechanics/RELEASE-SCHEDULE.md
Labels: approved, cla: yes, lgtm, size/XS

#368 Add chizhg to Knative Milestone Maintainers
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#371 Add permissions for Knative Release Leads
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#370 Add zhaojizhuang to the knative members list
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#374 Add candidates list, TOC.
  elections/2020/SC/README.md
  elections/2020/SC/voters.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#325 add actions-kind, drop temp group for actions
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/S

#372 Update Release Leads for 0.20
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#369 fix typo sc election2020 nomination
  elections/2020/SC/csantanapr.md
Labels: approved, cla: yes, lgtm, size/S

#376 Update knative.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#377 Add youssb to knative contibutors
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#348 Add the upcoming releases & k8s min versions
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: approved, cla: yes, lgtm, size/L

#380 Clarify who's being addressed by Goasguen's application
  elections/2020/SC/goasguen.md
Labels: approved, cla: yes, lgtm, size/XS

#378 Adds details for trademark committee
  TRADEMARK-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/S

#379 add members from kperf and kn-plugin-admin
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#384 Add self to knative-sandbox team members
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#382 Removing nachocano from Sources WG leads
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#387 Update knative.yaml & knative-sandbox.yaml: Add myself
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
