Repository knative/community, pull requests merged in 2020-02, with the labels that each got.

#71 Add lionelvillard as Eventing working group lead
  WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#78 Updates steering seat to be VMware instead of Pivotal
  STEERING-COMMITTEE.md
Labels: approved, lgtm, size/XS

#79 Make it possible for TOC members to maintain WORKING-GROUPS.md
  OWNERS_ALIASES
  WORKING-GROUPS.md
  working-groups/OWNERS
  working-groups/WORKING-GROUPS.md
Labels: approved, lgtm, size/XL

#82 remove links to VCs, point to notes
  working-groups/WORKING-GROUPS.md
Labels: approved, lgtm, size/S

#83 Add grantr as Eventing WG lead
  working-groups/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#98 Step down as an Operations WG lead
  working-groups/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#100 cppforlife stepping down as WG lead.
  working-groups/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS

#99 Add Dave Protasowski as Serving API Core WG technical lead.
  working-groups/WORKING-GROUPS.md
Labels: approved, lgtm, size/XS
