Repository knative/community, pull requests merged in 2020-06, with the labels that each got.

#146 Reconcile the members of the ToC after election.
  TECH-OVERSIGHT-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/S

#149 Update REPOSITORY-GUIDELINES to include knative-sandbox.
  REPOSITORY-GUIDELINES.md
Labels: approved, cla: yes, lgtm, size/L

#148 Reconcile ToC members in OWNER_ALIASES.
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#150 New Google representatives in steering
  STEERING-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/XS

#135 Initial Peribolos configuration for knative and knative-sandbox
  peribolos/OWNERS
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XXL

#160 Reflect the sample-controller migration in peribolos
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#156 Add pierDipi to knative-sandbox members
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#157 Add eventing-kafka-broker to knative-sandbox peribolos repos
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#161 Re-add Harwayne (WG lead) who was removed in the great absent user scrub of 2020
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#159 Add knative-prow-robot as an org admin
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#162 Fix Peribolos error
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#164 Add two users who were added manually after #135
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#163 Change min K8s version to reflect reality
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: approved, cla: yes, lgtm, size/S

#165 Add two milestone maintainers which were added after #135
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#168 Move sample-source to knative-sandbox
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#171 Rename Abd4llA to devguyio
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS
