Repository knative/community, pull requests merged in 2020-12, with the labels that each got.

#390 Update new repo template to link the prow guide
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: approved, cla: yes, lgtm, size/XS

#394 Allow TOC to manage .github directory
  .github/OWNERS
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#391 Add myself to knative-sandbox org
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#398 Add Jimmy Lin (zhongduo) to knative-sandbox member
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#397 Add Haolicopter to knative and knative sandbox members
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#395 Document repo prefixes assigned to working groups.
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/M

#393 Add kn-plugin-source-kamelet to peribolos configuration
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#388 Create BRANDING.MD
  BRANDING.MD
Labels: approved, cla: yes, lgtm, size/M, trademark

#400 Updates steering committee's email group
  STEERING-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/XS

#346 doc-migrate tool to copy files and mirror folders
  mechanics/tools/gdocs-migrate/client.go
  mechanics/tools/gdocs-migrate/forest.go
  mechanics/tools/gdocs-migrate/go.mod
  mechanics/tools/gdocs-migrate/go.sum
  mechanics/tools/gdocs-migrate/main.go
Labels: approved, cla: yes, lgtm, size/XXL

#399 Updates steering members based on 2020 elections
  OWNERS_ALIASES
  STEERING-COMMITTEE.md
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#401 Add a Golang policy
  mechanics/GOLANG-POLICY.md
Labels: approved, cla: yes, lgtm, size/M

#403 Adds Knative 2020 Annual Report
  annual_reports/Knative 2020 Annual Report.pdf
Labels: approved, cla: yes, lgtm, size/XS

#404 Update Eventing WG to new Knative Drive links
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#405 Add net-ingressv2 to peribolos configuration
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XS

#406 Remove duplicatd user in admin and member role
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, kind/bug, lgtm, size/XS
