Repository knative/community, pull requests merged in 2020-09, with the labels that each got.

#238 Add aavarghese to members list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#249 Make it so the folks doing github actions exploring in sandbox can make releases
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/S

#248 Add AlexandraRoatis to the members list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#142 Fix `</td` tag close in ROLES.md
  ROLES.md
Labels: approved, cla: yes, lgtm, size/XS

#250 This revises the new-repo template to be more self-service.
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: approved, cla: yes, lgtm, size/M

#251 add tom24d to members
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#253 Add devguyio to Milestone Maintiners and sort the list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/M

#256 Add joshua-bone to members.
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#254 Adding reconciler-test to repo config for sandbox
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#265 Removes past steering members from owners file
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#266 Make projected minimum kubernetes versions more true
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: approved, cla: yes, lgtm, size/S

#267 Update my whereabout
  TECH-OVERSIGHT-COMMITTEE.md
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#268 Remove unnecessary whitelist terminology.
  elections/2020/README.md
Labels: approved, cla: yes, lgtm, size/XS

#264 Add kn-plugin-admin to the peribolos sandbox config
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#269 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#261 Add eventing-XXX to repo config for sandbox
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/M

#271 Add April to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#228 Document oncall rotation participation.
  ROLES.md
Labels: approved, cla: yes, lgtm, size/XS

#273 Note that the Projects menu may not work
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: approved, cla: yes, lgtm, size/XS

#274 Setting Zhimin and Scott for 0.18 release leads.
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#272 Remove people with failed org invites from Peribolos
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#276 Add kperf to the peribolos sandbox config
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#278 Add joshua-bone as knative developer
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#285 Add Harwayne to Eventing Triage
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#279 Rick R. member of sandbox
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#286 Add eclipselu to members list
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#280 Add joshuawilson to members list
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#287 Removing Sam as Doc WG lead
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#290 Followup to #287 removing samodell from peribolos
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#277 Define (charter) Steering and Trademark Committees
  GOVERNANCE.md
  STEERING-COMMITTEE.md
  TRADEMARK-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/XL

#292 Add arghya88 to members list
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#294 Fix peribolos config file for Knative by removing jessiezcc
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#263 Add some extra explanation to new-repo issue template
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: approved, cla: yes, lgtm, size/S

#299 Set min K8s version to v1.17.x for the 0.18.x releases
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: approved, cla: yes, lgtm, size/XS

#302 Add eventing-redis to knative-sandbox peribolos
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#297 added kn-plugin-source-pkg to knative-sandbox
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#300 add eventing-autoscaler-keda to eventing writers
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#305 chaodaiG step down as productivity WG lead
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#304 Add aavarghese to knative-sandbox members list
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS
