Repository knative/community, pull requests merged in 2020-04, with the labels that each got.

#117 Fix the link to `DOCS-CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: approved, cla: yes, lgtm, size/XS

#111 Add notes on roles
  ROLES.md
Labels: approved, cla: yes, lgtm, size/M

#119 Add TOC election mechanics and eligibility criteria
  TECH-OVERSIGHT-COMMITTEE.md
  mechanics/TOC.md
Labels: approved, cla: yes, lgtm, size/M

#121 Add Chi Zhang as Productivity WG technical lead.
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#73 Delegate WG membership and technical process documentation to the TOC
  mechanics/OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#118 Added Feature Tracks link to process/guidelines
  mechanics/README.md
Labels: approved, cla: yes, lgtm, size/XS

#122 Add directions for importing calendar to WORKING-GROUPS.md
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/S

#123 Remove WORKING-GROUPS.md link to remove duplicate headings from website.
  CONTRIBUTING.md
  README.md
  SLACK-GUIDELINES.md
  STEERING-COMMITTEE.md
  WORKING-GROUPS.md
  docs/DOCS-CONTRIBUTING.md
  docs/README.md
  mechanics/WORKING-GROUP-PROCESSES.md
Labels: approved, cla: yes, lgtm, size/S

#30 Initial markdown transcription of Release Versioning doc
  mechanics/README.md
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: approved, cla: yes, lgtm, size/XXL

#124 Run prettier after #123
  CONTRIBUTING.md
  README.md
  SLACK-GUIDELINES.md
  STEERING-COMMITTEE.md
  docs/DOCS-CONTRIBUTING.md
  docs/README.md
  mechanics/WORKING-GROUP-PROCESSES.md
Labels: approved, cla: yes, lgtm, size/L

#126 Add April Kyle Nassi to Steering
  STEERING-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/S

#127 Adding 2020 TOC election details
  elections/2020/README.md
  elections/2020/voters.md
  elections/README.md
  mechanics/TOC.md
Labels: approved, cla: yes, lgtm, size/L

#128 remove vaikas from TOC due to upcoming elections
  TECH-OVERSIGHT-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/XS

#105 Update the process for creating a new working group.
  mechanics/WORKING-GROUP-PROCESSES.md
Labels: approved, cla: yes, lgtm, size/M

#97 renaming the channels wg to 'Event Delivery'
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#129 Clarify parts of the election mechanics
  elections/README.md
Labels: approved, cla: yes, lgtm, size/S
