Repository knative/community, pull requests merged in 2021-01, with the labels that each got.

#408 Add Ahmed to Eventing WG leads
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#407 Update links for knative.team docs and calendar
  CONTRIBUTING.md
  TECH-OVERSIGHT-COMMITTEE.md
  mechanics/FEATURE-TRACKS.md
  mechanics/WORKING-GROUP-PROCESSES.md
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#411 Update API Core details in WORKING-GROUPS.md
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#358 Remove my old github username from the voters file
  elections/2020/SC/voters.md
Labels: approved, cla: yes, lgtm, size/XS

#375 Update STEERING-COMMITTEE.md
  STEERING-COMMITTEE.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#413 add nlopezgi to Knative Milestone Maintainers
  peribolos/knative.yaml
Labels: approved, cla: yes, kind/documentation, lgtm, size/XS

#416 adding kthakar1990 to knative and knative sandbox members
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#417 Be more explicit about not changing the logo
  BRANDING.MD
Labels: approved, cla: yes, lgtm, size/XS

#418 Fix link to eventing WG agenda doc
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#422 adding steven0711dong to knative and knative sandbox members
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#419 add myself to the members list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS
