Repository knative/community, pull requests merged in 2021-07, with the labels that each got.

#671 Update WORKING-GROUPS.md
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#649 Add kn-plugin-func entries for peribolos
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XS

#672 Rename beemarie to bvennam
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#674 Adding salably to members list
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#673 Update WORKING-GROUPS.md
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/M

#675 Peribolos test - please ignore
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#678 Add @vyasgun to both orgs
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#679 Removed myself
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/S

#677 Remove test and to-import repo from peribolos
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/S

#682 Add Peter Tran to peribolos
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#683 Fix for @dolfolife's Github name update
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#684 Remove stray occurrences of kn-plugin-func
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#687 Add kn-func-plugin to peribolos
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/S

#690 Regenerate OWNERS_ALIASES for knative-sandbox
  knative-sandbox-OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#694 Remove vaikas as eventing wg lead
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#695 add kn-plugin-quickstart approvers github team
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/S

#689 Creates ADOPTERS.MD file
  ADOPTERS.MD
Labels: approved, cla: yes, lgtm, size/S

#697 regen owner_aliases
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#692 Add proposed format for emeritus for TOC
  TECH-OVERSIGHT-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/S

#691 Changing @pmorie's organization
  STEERING-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/XS

#685 add @snneji as approver/docs-writters
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#698 add emeritus for SC
  STEERING-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/S

#703 Add psschwei as a serving reviewer
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#701 add grantr and vaikas to emeritus WG leads
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#705 Add adopters up to July 23
  ADOPTERS.MD
Labels: approved, cla: yes, lgtm, size/S

#686 Add RichardJJG as approver/docs-writter
  OWNERS_ALIASES
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#669 Updating Knative Brand Guidelines
  BRANDING.MD
  icons/logo.svg
Labels: approved, cla: yes, kind/documentation, lgtm, ok-to-test, size/L

#704 Update for client repos
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#708 Make David Simansky a Client WG Lead
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#707 Update ADOPTERS.MD
  ADOPTERS.MD
Labels: approved, cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#710 add vaikas to eventing writers
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#713 Fixes broken link in ADOPTERS.MD
  ADOPTERS.MD
Labels: approved, cla: yes, lgtm, size/XS

#712 Add emeritus section for the client WG
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#711 Add tcnghia to to emeritus WG leads
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#714 update emeritus API leads and older working groups
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/S

#715 update the release leads for 0.25
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#716 Drop last occurrence of peribolos test repo
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#717 Make dsimansk working group lead in WORKING_GROUPS.md
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#676 Provide command to generate Slack reminders
  mechanics/TOC-REVIEW.schedule
Labels: approved, cla: yes, lgtm, size/XS

#718 Adds adopters up to jul 29th
  ADOPTERS.MD
Labels: approved, cla: yes, lgtm, size/XS

#719 fix date format to what slack wants
  mechanics/TOC-REVIEW.schedule
Labels: approved, cla: yes, lgtm, size/XS
