Repository knative/community, pull requests merged in 2021-03, with the labels that each got.

#494 Switch to the 0.22 release leads
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#509 add sbawaska to knative-sandbox/eventing-rabbitmq approvers
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#508 Specs repo peribolos changes + Conformance WG
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#510 Add peribolos note
  ROLES.md
Labels: approved, cla: yes, lgtm, size/XS

#511 Updating control-protocol approvers
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#493 Add wzshiming to the members list
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#504 grant doc writers write access to release repo
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#480 Adds details about TM meeting
  TRADEMARK-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/XS

#514 link 2020 election instead of TBD
  elections/README.md
Labels: approved, cla: yes, lgtm, size/XS

#515 Add fallback-notification-blocker to peribolos config
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#513 Adds governance details around sandbox repos
  ROLES.md
Labels: approved, cla: yes, lgtm, size/XS

#516 Add security subdirectory for security WG.
  working-groups/security/OWNERS
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XS

#518 Add tayarani as Comformance WG lead
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#519 Drop mattmoor from TOC groups
  OWNERS_ALIASES
  TECH-OVERSIGHT-COMMITTEE.md
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/S

#521 Remove bouncing/blocked users
  peribolos/knative.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#512 Add Security Response Policy
  working-groups/security/responding.md
Labels: approved, cla: yes, lgtm, size/L

#525 Drop unnecessary occurrences of master
  .github/ISSUE_TEMPLATE/new-repo.md
  CONTRIBUTING.md
  README.md
  REPOSITORY-GUIDELINES.md
  ROLES.md
  STEERING-COMMITTEE.md
  docs/README.md
  elections/2020/SC/README.md
  elections/2020/TOC/README.md
  mechanics/CREATING-A-SANDBOX-REPO.md
  mechanics/FEATURE-TRACKS.md
  mechanics/SC.md
  mechanics/TOC.md
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/M

#529 Fix the Scaling WG doc
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#530 Shared drive link updated
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#151 Address grantr feedback on #149
  REPOSITORY-GUIDELINES.md
Labels: approved, cla: yes, lgtm, size/M

#531 Add links to new content templates
  docs/README.md
  docs/new-page-template.md
Labels: approved, cla: yes, lgtm, size/M

#528 add homebrew-kn-plugins to knative-sandbox
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/S

#538 Link to example of working group creation process
  mechanics/WORKING-GROUP-PROCESSES.md
Labels: approved, cla: yes, lgtm, size/XS

#537 Add Ron as an actual org member
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#532 Automate creation of OWNERS_ALIASES
  OWNERS_ALIASES
  docs/OWNERS
  hack/update-codegen.sh
  mechanics/tools/gen-aliases/go.mod
  mechanics/tools/gen-aliases/go.sum
  mechanics/tools/gen-aliases/main.go
  working-groups/security/OWNERS
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XXL

#535 Check in initial VMT rotation
  working-groups/security/vmt.rotation
Labels: approved, cla: yes, lgtm, size/S

#534 add trademark committee doc to "toc"
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#543 Remove user deleted from GitHub
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#229 Initial commit of "Knative Migration-To-Core Process"
  mechanics/MATURITY-LEVELS.md
Labels: approved, cla: yes, lgtm, size/L
