Repository knative/community, pull requests merged in 2021-10, with the labels that each got.

#788 Add next quarter of WG reviews
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S, cla: yes

#790 Add nealhu as a serving reviewer
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes

#816 Fix Electo link
  elections/2021-SC/README.md
Labels: lgtm, approved, size/XS, cla: yes, kind/bug
