Repository knative/community, pull requests merged in 2021-05, with the labels that each got.

#598 Remove emeritus members from teams
  OWNERS_ALIASES
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#599 Add kntaive-prow-updater-robot to knative and knative-sandbox org
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#595 Create CONSENSUS.md
  CONSENSUS.md
Labels: approved, cla: yes, lgtm, size/M

#600 add myself to approver memberlist
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#604 skip this week, adjust
  mechanics/TOC-REVIEW.schedule
Labels: approved, cla: yes, lgtm, size/S

#605 Regenerate OWNERS_ALIASES
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#606 add psschwei to members list
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#610 Remove jszroberto
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#608 remove peterfeifanchen from knative/knative-sandbox
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#607 Reschedule observability to 20 May.
  mechanics/TOC-REVIEW.schedule
Labels: approved, cla: yes, lgtm, size/S

#611 Fix eventing-kafka-broker Eventing Writers access
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#617 Org membership
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#619 Update release leads for 0.24 -> dprotaso,matzew
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#616 Update productivity approvers and reviewers
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#614 Add results of 2021 TOC election to Elekto App.
  elections/2021-TOC/results.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#627 Add Rodolfo
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#625 Remove company limits for TOC
  mechanics/TOC.md
Labels: approved, cla: yes, lgtm, size/XS

#524 Add initial threat model document
  working-groups/security/threat-model.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/M

#628 Networking WG Leads -= { tcnghia }
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#632 Adding eric-sap as eventing-kafka approver
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#633 Add self as member to knative.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#634 Add self to knative-sandbox.yaml
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#630 Updated the TOC page with the final results of the 2021 TOC election
  TECH-OVERSIGHT-COMMITTEE.md
Labels: approved, cla: yes, lgtm, size/S

#637 Add novahe to the members list
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#638 Relax PST membership requirements
  working-groups/security/responding.md
Labels: approved, cla: yes, lgtm, size/XS

#624 Regenerate OWNERS_ALIASES
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#636 correct community meeting freq + add link to agenda
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#639 Add xinydev to the members list
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS
