Repository knative/community, pull requests merged in 2021-09, with the labels that each got.

#762 Add docs WG emeritus leads
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS, cla: yes

#764 Update TOC review schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S, cla: yes

#766 Replacing Brenda w/ Omer on ToC
  TRADEMARK-COMMITTEE.md
Labels: lgtm, approved, size/XS, cla: yes

#765 Add nainaz as a member to the knative community
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes, needs-ok-to-test

#763 Update Conformance, Trademark
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes

#756 Fix golang redirect sample PR link
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: lgtm, approved, size/XS, cla: yes, kind/bug

#758 Implement 731
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/M, cla: yes

#769 Removes bsnchan from steering
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS, cla: yes

#773 Adding Kogito Members to peribolos
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS, cla: yes

#771 vaikas no longer at VMware
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS, cla: yes

#770 Add bsnchan to SC emeritus
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS, cla: yes

#774 Add Iliia Khaprov @ VMware
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes, needs-ok-to-test

#757 run the scripts
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
Labels: lgtm, approved, size/S, cla: yes

#743 Adding container-freezer repo to peribolos
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/S, cla: yes

#768 fix issue 92
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
Labels: lgtm, approved, size/M, cla: yes

#776 Update SUNSETTING-FEATURES.md
  mechanics/SUNSETTING-FEATURES.md
Labels: lgtm, approved, size/XS, cla: yes

#777 Update TOC schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/XS, cla: yes

#780 Add three more releases to schedule.
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: lgtm, approved, size/L, cla: yes

#749 Add Eventing Kafka WG to community section
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
  working-groups/kafka/CHARTER.md
Labels: lgtm, approved, size/L, cla: yes

#781 Add nealhu @ IBM
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes, needs-ok-to-test

#782 add myself to the knative-sandbox members list
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS, cla: yes

#784 Update versions tables again, it turns out we had 3
  mechanics/RELEASE-SCHEDULE.md
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: lgtm, approved, size/XL, cla: yes

#734 2021 SC elections mechanics
  elections/2021-SC/OWNERS
  elections/2021-SC/README.md
  elections/2021-SC/candidate-template.md
Labels: lgtm, approved, size/L, cla: yes
