Repository knative/community, pull requests merged in 2021-12, with the labels that each got.

#856 Markus steps down as Autoscaling WG lead
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/M, cla: yes, kind/cleanup, kind/removal

#857 Add election results for 2021 SC
  elections/2021-SC/ballots.csv
  elections/2021-SC/results.md
Labels: lgtm, approved, size/M, cla: yes

#859 Document roadmap process
  mechanics/ROADMAPS.md
Labels: lgtm, approved, size/M, cla: yes

#860 Update Steering Committee with the newly elected members
  OWNERS_ALIASES
  STEERING-COMMITTEE.md
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S, cla: yes

#863 Add Shashankft9 to knative and knative-sandbox members
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes, ok-to-test

#862 Include myself as a productivity reviewer
  OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes

#866 Omer stepping down from DUX
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#868 Add @snneji to knative-sandbox members
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#873 Add GSoC information pages
  google-summer-of-code/README.md
  google-summer-of-code/gsoc-2022.md
Labels: lgtm, approved, size/L

#855 Scott stepping down from Productivity WG
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S, cla: yes, kind/cleanup, kind/removal

#861 End user seat proposal.
  elections/2021-SC-EU/enduser.md
  elections/2021-SC-EU/nomination-template.md
  elections/2021-SC/README.md
Labels: lgtm, approved, size/M, cla: yes

#869 Remove kimsterv to fix peribolos CI runs
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#870 Add Paul Schweigert as docs approver (docs-writer)
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#875 Markus steps down from TOC
  OWNERS_ALIASES
  TECH-OVERSIGHT-COMMITTEE.md
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#872 Update release schedule
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS

#877 Fix Contributor seat => End User Seat.
  elections/2021-SC-EU/enduser.md
Labels: lgtm, approved, size/XS

#878 fix the incorrect project name
  ADOPTERS.MD
Labels: lgtm, approved, size/XS, needs-ok-to-test

#871 Update release leads for 1.2 release
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#879 Update schedule for holidays, extend review rotation.
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S
