Repository knative/community, pull requests merged in 2021-11, with the labels that each got.

#811 Add candidate for SC-2021 elections
  elections/2021-SC/candidate-csantanapr.md
Labels: lgtm, approved, size/S, cla: yes

#815 add lance as candidate for the 2021 SC elections
  elections/2021-SC/candidate-lance.md
Labels: lgtm, approved, size/S, cla: yes

#812 Swap in salaboy for eventing-rabbitmq reviewers
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS, cla: yes

#820 Candidate typo and fixed link to voters.yaml
  elections/2021-SC/README.md
  elections/2021-SC/candidate-lball.md
Labels: lgtm, approved, size/XS, cla: yes

#818 Adding aliok as an approver for eventing-kafka-broker
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS, cla: yes

#822 Add myself to knative-sandbox & knative members
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes, ok-to-test

#824 Update release leads for 1.1 release
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M, cla: yes

#819 Update affiliations for Ville and Paul
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS, cla: yes, kind/documentation

#825 Update release schedule
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS, cla: yes

#826 add naina and omer as approvers
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS, cla: yes

#821 Create candidate-sebgoa.md
  elections/2021-SC/candidate-sebgoa.md
Labels: lgtm, approved, size/S, cla: yes

#828 Fix elections.yaml so that affiliation shows on candidate profiles.
  elections/2021-SC/election.yaml
Labels: lgtm, approved, size/XS, cla: yes, kind/bug

#831 Voter exceptions
  elections/2021-SC/election.yaml
  elections/2021-SC/voters.yaml
Labels: lgtm, approved, size/XS, cla: yes

#830 Adding omerbensaadon's candidacy
  elections/2021-SC/candidate-omerbensaadon.md
Labels: lgtm, approved, size/M, cla: yes

#829 Update SC.md
  mechanics/SC.md
Labels: lgtm, approved, size/XS, cla: yes

#832 adding murugappan as candidate for sc
  elections/2021-SC/candidate-itsmurugappan.md
Labels: lgtm, approved, size/S, cla: yes

#834 Add myself as a candidate for Steering Election
  elections/2021-SC/candidate-xtreme-sameer-vohra.md
Labels: lgtm, approved, size/M, cla: yes

#836 Change the number of elected seats in this election properly to two.
  elections/2021-SC/README.md
  elections/2021-SC/election.yaml
  elections/2021-SC/election_desc.md
Labels: lgtm, approved, size/S, cla: yes

#837 fixed several links and corrected a mistake in the voter exception deadline
  elections/2021-SC/README.md
Labels: lgtm, approved, size/XS, cla: yes

#833 Add pierDipi to eventing-kafka approvers
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS, cla: yes

#835 remove parenthesis
  README.md
Labels: lgtm, approved, size/XS, cla: yes

#823 add nader-ziada as reviewer for serving and scaling
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes

#839 fix the filename
  README.md
Labels: lgtm, approved, size/XS, cla: yes

#841 Add Control Plane to Adopters
  ADOPTERS.MD
Labels: lgtm, approved, size/M, cla: yes, needs-ok-to-test, kind/documentation

#842 update adopters
  ADOPTERS.MD
Labels: lgtm, approved, size/M, cla: yes

#845 Add snneji as Docs + UX WG lead
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S, cla: yes

#847 approved exception requests for SC election voting
  elections/2021-SC/voters.yaml
Labels: lgtm, approved, size/XS, cla: yes

#848 Replace Omer Bensaadon with Evan Anderson as VMware Trademark representative
  OWNERS_ALIASES
  TRADEMARK-COMMITTEE.md
  peribolos/knative.yaml
Labels: lgtm, approved, size/S, cla: yes

#849 final exception for SC election
  elections/2021-SC/voters.yaml
Labels: lgtm, approved, size/XS, cla: yes

#850 Update Eventing Sources WG meeting date
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS, cla: yes

#846 Add verify-codegen workflow
  .github/workflows/verify.yaml
Labels: lgtm, approved, size/M, cla: yes

#838 Update our min K8s version principle to exclude releases in maintenance mode
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: lgtm, approved, size/S, cla: yes

#853 Fix the TZ conversion to PST.
  elections/2021-SC/README.md
Labels: lgtm, approved, size/XS, cla: yes

#851 Update the Knative on Alibaba Cloud website
  ADOPTERS.MD
Labels: lgtm, approved, size/XS, cla: yes, needs-ok-to-test
