Repository knative/community, pull requests merged in 2021-04, with the labels that each got.

#545 Fixed a typo
  docs/README.md
Labels: approved, cla: yes, lgtm, size/XS

#547 Add charters for all WGs that have them.
  working-groups/WORKING-GROUPS.md
  working-groups/client/CHARTER.md
  working-groups/delivery/CHARTER.md
  working-groups/docs/CHARTER.md
  working-groups/operations/CHARTER.md
  working-groups/productivity/CHARTER.md
  working-groups/security/CHARTER.md
  working-groups/sources/CHARTER.md
Labels: approved, cla: yes, lgtm, size/XL

#539 Add minimal SECURITY.md
  SECURITY.md
Labels: approved, cla: yes, lgtm, size/XS

#555 Add lberk to the list of eventing-kafka approvers
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#526 TOC 2021 Election Process
  elections/2021-TOC/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#552 Add groups based on observed usage in knative repos
  OWNERS_ALIASES
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/L

#558 tcnghia@ vaikas@ -> Knative Release Leads for 0.23
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#560 Adds details to TOC elections about company limitations
  mechanics/TOC.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/XS

#564 Add voters.yaml file.
  elections/2021-TOC/voters.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#565 remove vaikas from eventing-sources leads
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#559 Update time for docs WG meeting
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#568 Specifies that vendor limitations do not restrict candidate eligibility
  mechanics/TOC.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/XS

#567 Update knative.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#536 Check in initial TOC review schedule
  mechanics/TOC-REVIEW.schedule
Labels: approved, cla: yes, lgtm, size/S

#573 Add julz to API Approvers
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#574 Add pmbanugo to the Doc group
  peribolos/knative.yaml
Labels: approved, cla: yes, kind/documentation, lgtm, needs-ok-to-test, size/XS

#575 Regenerate OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#577 Add benmoss to members
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#578 Update TOC to reflect changes in election system
  mechanics/TOC.md
Labels: approved, cla: yes, kind/bug, kind/documentation, lgtm, size/XS

#569 Evan TOC candidacy.
  elections/2021-TOC/candidate-evana.md
Labels: approved, cla: yes, kind/enhancement, lgtm, size/S

#572 Adding Scott for ToC 2021 Election
  elections/2021-TOC/candidate-n3wscott.md
Labels: approved, cla: yes, lgtm, size/S

#576 dprotaso's TOC candidacy submission
  elections/2021-TOC/candidate-dprotaso.md
Labels: approved, cla: yes, lgtm, size/S

#582 Fix formatting in Scott Nichol's profile for Elekto.
  elections/2021-TOC/candidate-evankanderson.md
  elections/2021-TOC/candidate-n3wscott.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#580 changing times of Docs + UX to reflect actual meeting times
  working-groups/WORKING-GROUPS.md
Labels: approved, cla: yes, lgtm, size/XS

#548 Update SLACK-GUIDELINES.md
  SLACK-GUIDELINES.md
Labels: approved, cla: yes, lgtm, size/S

#557 Move docs contrib to help section
  docs/README.md
  docs/_index.md
Labels: approved, cla: yes, lgtm, size/M

#587 adding Ahmed to eventing-kafka
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#592 Add two voters per approved exception requests.
  elections/2021-TOC/voters.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#586 Add OWNERS_ALIASES for knative-sandbox
  hack/update-codegen.sh
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/L

#596 future->feature
  mechanics/SUNSETTING-FEATURES.md
Labels: approved, cla: yes, lgtm, size/XS
