Repository knative/community, pull requests merged in 2021-06, with the labels that each got.

#629 Add kn-plugin-quickstart repo under knative-sandbox
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#635 Add new TOC members
  OWNERS_ALIASES
  TECH-OVERSIGHT-COMMITTEE.md
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/M

#631 Add initial disclosure policy based on Istio's
  working-groups/security/disclosure.md
Labels: approved, cla: yes, lgtm, size/L

#620 Revisit rules around what happens when a TOC member resigns
  mechanics/TOC.md
Labels: approved, cla: yes, lgtm, size/S

#640 Updated Elekto results page with the final TOC election results
  elections/2021-TOC/results.md
Labels: approved, cla: yes, lgtm, size/S

#594 Add section about updating docs
  REPOSITORY-GUIDELINES.md
Labels: approved, cla: yes, lgtm, size/XS

#641 Add bbtong to the members list
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#645 Fix link to Feature Tracks doc
  mechanics/FEATURE-TRACKS.md
Labels: approved, cla: yes, lgtm, size/L

#646 add psschwei to knative-sandbox as member org
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#643 Update and extend TOC review schedule
  mechanics/TOC-REVIEW.schedule
Labels: approved, cla: yes, lgtm, size/S

#650 Remove nlopezgi from knative owner file
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#647 Remove Jimmy (zhongduo) from knative owner file
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#651 Join knative GH Org
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#652 Join knative-sandbox organization
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#653 [repo-request] knative-sandbox/monitoring
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/S

#658 Re-run peribolos automation. I need to make this not run by hand...
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#659 include 0.24 release in release version table
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: approved, cla: yes, lgtm, size/M

#661 Add Spencer to Trademark
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#655 Update README.md - Reference Consensus
  mechanics/README.md
Labels: approved, cla: yes, lgtm, size/XS

#662 add @impl to knative/knative-sandbox org
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS

#660 Mention source-of-truth location
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  mechanics/tools/gen-aliases/main.go
Labels: approved, cla: yes, lgtm, size/S

#663 Regenerate OWNERS_ALIASES with spencerdillard
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#668 Adds Spencer to TM committee
  TRADEMARK-COMMITTEE.md
Labels: approved, cla: yes, kind/documentation, lgtm, size/S

#664 Shift TOC updates by one week as we missed the productivity update
  mechanics/TOC-REVIEW.schedule
Labels: approved, cla: yes, lgtm, size/S

#670 Adding myself to the peribolos
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: approved, cla: yes, lgtm, size/XS
