Repository knative/community, pull requests merged in 2021-08, with the labels that each got.

#721 Add jrangelramos per kn-plugin-func #447
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, lgtm, size/XS

#723 Adjust schedule due to missed 29 July presentation
  mechanics/TOC-REVIEW.schedule
Labels: approved, cla: yes, lgtm, size/S

#720 Add Travis and Eric from SAP to control-protocol approvers.
  peribolos/knative-sandbox.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#722 Remove @vagababov as Scaling WG lead
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS, cla: yes

#725 add KubeSphere, Liquidx
  ADOPTERS.MD
Labels: lgtm, approved, size/S, cla: yes

#726 Regenerate OWNERS_ALIASES to reflect latest config
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
Labels: lgtm, approved, size/S, cla: yes

#727 Update tools depedencies to fix build issues
  mechanics/tools/gdocs-migrate/go.mod
  mechanics/tools/gdocs-migrate/go.sum
  mechanics/tools/gen-aliases/go.mod
  mechanics/tools/gen-aliases/go.sum
Labels: lgtm, approved, cla: yes, size/XXL

#730 Add 0.25 release in release version table
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: lgtm, approved, size/M, cla: yes

#729 remove gdocs-migrate tool
  mechanics/tools/gdocs-migrate/.gitignore
  mechanics/tools/gdocs-migrate/README.md
  mechanics/tools/gdocs-migrate/client.go
  mechanics/tools/gdocs-migrate/forest.go
  mechanics/tools/gdocs-migrate/go.mod
  mechanics/tools/gdocs-migrate/go.sum
  mechanics/tools/gdocs-migrate/main.go
  mechanics/tools/gdocs-migrate/oauth.go
Labels: lgtm, approved, cla: yes, size/XXL

#733 Fix link to emeritus committee members
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS, cla: yes

#736 v0.26 release leads
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S, cla: yes

#739 Add Ricardo Zanini to peribolos
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes, ok-to-test, kind/documentation

#735 add jberkus as member
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes

#740 add Optum
  ADOPTERS.MD
Labels: lgtm, approved, size/XS, cla: yes

#741 Add josephburnett as scaling emeritus lead
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS, cla: yes

#744 Add psschwei as autoscaling reviewer
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes

#748 Add g3n-github-robot account to the knative and knative-sandbox org
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes

#747 Add bmo to rabbitmq approvers
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS, cla: yes

#745 Add eventing-kogito repository to peribolos
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/S, cla: yes

#732 Scott stepping down from Sources WG
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/L, cla: yes, kind/cleanup, kind/removal

#738 Removing the delivery, which will go back to the eventing WG realm
  working-groups/WORKING-GROUPS.md
  working-groups/delivery/CHARTER.md
Labels: lgtm, approved, size/L, cla: yes

#752 Add the emeritus leads fo the operation work group
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS, cla: yes

#761 Adding senthilnathan to members list
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, cla: yes, needs-ok-to-test
