Repository knative/community, pull requests merged in 2022-08, with the labels that each got.

#1140 Fix Release Dates
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/M

#1139 Add security-guard repo
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/S

#1142 Add chzhyang to kperf approvers
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1143 Add EasyCLA step to new repo checklist
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: lgtm, approved, size/XS

#1144 Add psschwei as serving WG lead
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS

#1128 added astelmashenko as Knative Sandbox member
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1145 update release leads for 1.7
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1147 chore: remove SAP from adopters list
  ADOPTERS.MD
Labels: lgtm, approved, size/XS, kind/cleanup

#1148 Update Scotts company affiliation
  TECH-OVERSIGHT-COMMITTEE.md
Labels: lgtm, approved, size/XS

#1109 chore: remove func from knative org in peribolos
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/M

#1149 csantanapr step down as dux wg lead
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1150 1.8 is next, and 1.7 is a done deal
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS

#1153 Add jrangelramos to kn-plugin-func approvers
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS
