Repository knative/community, pull requests merged in 2022-01, with the labels that each got.

#852 Add myself to eventing-rabbitmq approvers
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS, cla: yes

#882 Fix broken link to DOCS-CONTRIBUTING.md
  CONTRIBUTING.md
Labels: lgtm, approved, size/XS, needs-ok-to-test

#883 Clean up language around TOC vacancies
  mechanics/TOC.md
Labels: lgtm, approved, size/S

#884 Updating TOC schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S

#886 Add Carlisia as approver
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#888 Create candidate-sebgoa.md
  elections/2021-SC-EU/candidate-sebgoa.md
Labels: lgtm, approved, size/S

#887 fix link to mechanics doc
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: lgtm, approved, size/XS

#880 Add SAP Event Mesh to ADOPTERS
  ADOPTERS.MD
Labels: lgtm, approved, size/XS, kind/documentation

#889 Update releease schedule
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/S

#890 Add @n3wscott to TOC.
  TECH-OVERSIGHT-COMMITTEE.md
Labels: lgtm, approved, size/S

#892 Update ADOPTERS.MD
  ADOPTERS.MD
Labels: lgtm, approved, size/XS

#893 update coc for SC to be responsible.
  CODE-OF-CONDUCT.md
Labels: lgtm, approved, size/XS

#891 move enduser election doc to readme
  elections/2021-SC-EU/README.md
  elections/2021-SC-EU/enduser.md
Labels: lgtm, approved, size/L

#894 Add skonto as reviewer for Serving API & Autoscaling
  OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#895 Add murugappan nominaton for end user sc seat
  elections/2021-SC-EU/candidate-itsmurugappan.md
Labels: lgtm, approved, size/S

#896 Add Bloomberg L.P. as adopter
  ADOPTERS.MD
Labels: lgtm, approved, size/XS, ok-to-test

#898 adding gabo1208 to the knative rabbitmq approvers group
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#899 Add Iliia Khaprov (VMware) as approver for eventing-rabbitmq
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#901 Update the link to ADOPTERS.MD in the SC end user election README
  elections/2021-SC-EU/README.md
Labels: lgtm, approved, size/XS, kind/documentation

#902 Update SECURITY.md
  SECURITY.md
Labels: lgtm, approved, size/XS, ok-to-test

#906 Add salaboy to kn-plugin-func-approvers
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#903 Add gab-satchi to knative and knative-sandbox
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#908 release v0.25 has EOL
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS

#904 Add chunyilyu
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#907 Add psschwei to productivity writers
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#910 Add cardil@ as productivity writer
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#915 update release leads for 1.3
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S
