Repository knative/community, pull requests merged in 2022-10, with the labels that each got.

#1174 Update time for alternate serving meeting
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS

#1175 added Mahamed Ali to our elections officer email group
  groups/committee-steering/groups.yaml
Labels: lgtm, approved, size/XS

#1176 Moved EU Seat info out of the elections section
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/S

#1170 chore: add entries for knative/func
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M

#1173 Changed deadline for new SC members to take office
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS

#1171 Initial docs required to run the 2022 SC election
  elections/2022-SC/OWNERS
  elections/2022-SC/README.md
  elections/2022-SC/election.yaml
  elections/2022-SC/election_desc.md
  elections/2022-SC/nomination-template.md
  elections/2022-SC/voters.yaml
Labels: lgtm, approved, size/L

#1178 Update security, docs, client WG times
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS

#1180 clarify end user in SC mechanic
  STEERING-COMMITTEE.md
  mechanics/SC.md
Labels: lgtm, approved, size/S

#1181 chore: update functions working group info
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS

#1182 add myself as member
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1164 Add squash merge commit options to repos
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  peribolos/validate-schema.py
Labels: lgtm, approved, size/L, kind/enhancement

#1183 Chainguard uses Knative in production.
  ADOPTERS.MD
Labels: lgtm, approved, size/XS

#1184 Removes inactive member to fix func owners issue
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1185 Update release schedule after 1.8 release
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS

#1189 Updating peribolos with TM committee changes
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1188 push back eventing and networking update
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S

#1190 chore(toc-review): update review schedule for holidays
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/XS
