Repository knative/community, pull requests merged in 2022-07, with the labels that each got.

#1110 Add new GKE RBAC group for a new cluster
  groups/groups_test.go
  groups/restrictions.yaml
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/M

#1107 Add xxinran to Knative and Knative Sandbox member
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1116 add myself to net-istio approvers
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1108 Fixed links to samples and contribution guidelines.
  README.md
Labels: lgtm, approved, size/XS, needs-ok-to-test, kind/documentation

#1117 Fixed / updated a few links
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/S

#1111 add Teresaliu as a member
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1121 Push back Serving WG update
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/M

#1122 Please add kellyaa as a member
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1106 please add chzhyang as a member
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1105 Update Trademark composition
  TRADEMARK-COMMITTEE.md
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1126 Davidhadas add member
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1129 add liuchangyan as a member
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1132 Added member haubenr
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1133 fixup peribolos *.ymls
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1135 Chi is no longer with us :(
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS

#1137 Re-add productivity wg leads to admin.
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1136 Add peribolos schema validation workflow
  .github/workflows/peribolos-schema-validate.yaml
  peribolos/validate-schema.py
Labels: lgtm, approved, size/M

#1138 Update Carlos' Org in steering
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS
