Repository knative/community, pull requests merged in 2022-03, with the labels that each got.

#933 Add kvmware to Release leads
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#940 Add `infra` repo
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#942 Copy logo PDF guidelines, including font and color guides, into the community branding guidelines.
  BRANDING.MD
  logo-guidelines.pdf
Labels: lgtm, approved, size/XS

#944 Remove sources-wg-lead as the sources WG is merged back to the Eventing WG
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#951 add knative/actions repo
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#965 Add Krsna and Mahamed as productivity writers
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#939 Add Pablo Mercado (@odacremolbap) as Eventing approver
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#975 Point CoC to CNCF's CoC
  CODE-OF-CONDUCT.md
Labels: lgtm, approved, size/M

#979 Extend TOC review schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S

#980 Remove sources WG from forthcoming TOC-schedule dates
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/M

#978 Add skonto in sandbox
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#977 Ahmed stepping down from eventing and eventing-kafka wg leads and approvers
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S, kind/cleanup, kind/removal

#983 Add caniszczyk and thelinuxfoundation as org OWNERS
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#982 remove efiturri who's not working on Knative anymore
  OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#990 Clean up obsolete info about GSoC - 2
  google-summer-of-code/README.md
Labels: lgtm, approved, size/XS

#937 Reconcile GSuite Groups
  groups/README.md
  groups/committee-code-of-conduct/groups.yaml
  groups/committee-oversight/groups.yaml
  groups/committee-trademark/groups.yaml
  groups/config.yaml
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/M

#985 Update license file(s)
  LICENSE
  LICENSE-docs
Labels: lgtm, approved, size/XL, kind/cncf-infra

#981 Add gab-satchi to eventing-rabbitmq approvers
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#988 Update release leads for v1.4
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M

#971 adding myself as a member of knative
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test
