Repository knative/community, pull requests merged in 2022-11, with the labels that each got.

#1191 nak3 stepping down from Networking WG
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1192 Lionel stepping down as eventing lead
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1193 Create candidate-salaboy.md
  elections/2022-SC/candidate-salaboy.md
Labels: lgtm, approved

#1197 Fix salaboy's entry
  elections/2022-SC/OWNERS
  elections/2022-SC/candidate-salaboy.md
Labels: lgtm, approved, size/S

#1198 Add lionel as eventing writer
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1199 Updates to security / eventing sources emeritus tables
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1201 please let me in
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1202 Voter exceptions for 2022 SC Election
  elections/2022-SC/voters.yaml
Labels: lgtm, approved, size/XS

#1203 Voter exceptions for 2022 SC Election - II
  elections/2022-SC/voters.yaml
Labels: lgtm, approved, size/XS

#1204 Add self nomination for 2022 SC election
  elections/2022-SC/candidate-aslom.md
Labels: lgtm, approved, size/S

#1206 SC 2022 self nomination for candidate smoser-ibm.md
  elections/2022-SC/candidate-smoser-ibm.md
Labels: lgtm, approved, size/S

#1208 Fixing smoser-ibm candidate profile format
  elections/2022-SC/candidate-smoser-ibm.md
Labels: lgtm, approved, size/XS

#1205 Add member norman465
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1207 Adding Naina Singh candidancy profile for SC elections
  elections/2022-SC/candidate-nainaz.md
Labels: lgtm, approved, size/S

#1200 Merge serving and networking working groups
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/M

#1210 Update TOC Review Schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/M

#1196 Adding scaling-group repo to peribolos
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/S

#1211 Fixing pierDipi's eligibility in voters.yaml
  elections/2022-SC/voters.yaml
Labels: lgtm, approved, size/XS

#1213 Update release leads for v1.9
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1212 Add creydr as a knative and knative-sandbox member
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1215 voters.yaml update for AngeloDanducci
  elections/2022-SC/voters.yaml
Labels: lgtm, approved

#1216 Fixed GH login case for several users in voters.yaml
  elections/2022-SC/voters.yaml
Labels: lgtm, approved, size/S

#1217 Added new IBM zSystems maintainer for knative projects
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS
