Repository knative/community, pull requests merged in 2022-12, with the labels that each got.

#1209 Add initial content for GSoC 23
  google-summer-of-code/README.md
  google-summer-of-code/gsoc-2023.md
Labels: lgtm, approved, size/M

#1223 drop alexellis due to compromised tokens
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1225 Add member izabelacg
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1226 dropping unused repo - kn-plugin-source-pkg
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/S

#1228 add new steering members
  STEERING-COMMITTEE.md
  groups/committee-steering/groups.yaml
  groups/groups.yaml
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M

#1230 Added 2022-SC-EU folder
  elections/2022-SC-EU/README.md
  elections/2022-SC-EU/nomination-template.md
Labels: lgtm, approved, size/M

#1221 proposal(func-go): adds knative-sandbox/func-go
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/M, kind/proposal

#1235 Changed SC-EU-Seat annoucment date to Dec 16
  elections/2022-SC-EU/README.md
Labels: lgtm, approved, size/XS

#1237 Adding gsoc idea for kne observability
  google-summer-of-code/gsoc-2023.md
Labels: lgtm, approved, size/S

#1232 Add myself to knative community members
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1233 Add myself to the community
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test
