Repository knative/community, pull requests merged in 2022-09, with the labels that each got.

#1154 Add cli leads to quickstart approvers
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/S

#1152 Keep supported releases in the first table
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS

#1155 :broom: Quarterly release cadence
  mechanics/RELEASE-SCHEDULE.md
  mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Labels: lgtm, approved, size/M

#1158 Add non knative.team addresses to steering folks.
  groups/committee-steering/groups.yaml
Labels: lgtm, approved, size/XS

#1160 Add jwcesign as a knative/knative sandbox member
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1162 Add missing word
  ROLES.md
Labels: lgtm, approved, size/XS

#1166 make steering world postable. Fix description.
  groups/committee-steering/groups.yaml
Labels: lgtm, approved, size/XS

#1167 Scott stepping down from ToC
  TECH-OVERSIGHT-COMMITTEE.md
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1168 update TOC members: add psschwei
  TECH-OVERSIGHT-COMMITTEE.md
  groups/committee-oversight/groups.yaml
  groups/groups.yaml
  groups/wg-productivity/groups.yaml
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1163 Update release leads for 1.8
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S
