Repository knative/community, pull requests merged in 2022-04, with the labels that each got.

#967 Fix logo guidelines; accidentally committed HTML
  logo-guidelines.pdf
Labels: lgtm, approved, size/XS

#973 Replace SVG logo with embedded PNG by proper SVG
  icons/logo.svg
Labels: lgtm, approved, size/L, needs-ok-to-test, kind/enhancement

#997 Clean up steering GSuite memberships
  groups/committee-steering/groups.yaml
Labels: lgtm, approved, size/XS

#996 Clean up GSuite groups
  groups/committee-oversight/groups.yaml
  groups/committee-trademark/groups.yaml
Labels: lgtm, approved, size/S

#998 Update productivity group membership
  groups/wg-productivity/OWNERS
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/XS

#999 Add Matt as TOC Member, clarified TOC election rules
  TECH-OVERSIGHT-COMMITTEE.md
  mechanics/TOC.md
Labels: lgtm, approved, size/S

#1001 drop the unused actions-kind repo
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1000 Add pierdipi as Eventing WG lead
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS

#994 Remove the transition block, since we have already transitioned to community elected SC.
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/S

#1004 Clarify end user appointment, vacancy and companies
  ADOPTERS.MD
  STEERING-COMMITTEE.md
  elections/2021-SC-EU/README.md
Labels: lgtm, approved, size/M

#1006 Add knative-automation bot account as the admin
  OWNERS_ALIASES
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1008 OWNERS filtering doesn't work for approvals - use symlinks instead
  OWNERS_ALIASES
  hack/update-codegen.sh
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
Labels: lgtm, approved, size/L

#1003 Add annual report 2021
  annual_reports/Knative 2021 Annual Report.pdf
Labels: lgtm, approved, size/XS

#1011 remove vaikas from eventing-writers
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1007 Nominate Krsna as the productivity WG lead
  groups/OWNERS
  groups/groups_test.go
  groups/wg-productivity/groups.yaml
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/M

#1012 Remove aryann from the knative peribolos config
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1013 Add label_sync prow job config
  label_sync/README.md
  label_sync/labels.yaml
Labels: lgtm, approved, size/L

#1014 Updating review schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/M

#943 Dicsontinue Eventing Source Working Group
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/M

#1015 Add @RamyChaabane to sandbox members
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1020 drop build-spike repo
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1018 Several updates with minor changes to the TOC election process
  mechanics/SC.md
  mechanics/TOC.md
Labels: lgtm, approved, size/S

#1010 drop filter since it applies only to labelling
  OWNERS
Labels: lgtm, approved, size/XS

#1019 Updating main election README to reflect how we are actually conducting elections
  elections/README.md
Labels: lgtm, approved, size/L

#1017 2022 TOC Elections framework
  elections/2022-TOC/OWNERS
  elections/2022-TOC/README.md
  elections/2022-TOC/election.yaml
  elections/2022-TOC/election_desc.md
  elections/2022-TOC/nomination-template.md
  elections/2022-TOC/voters.yaml
Labels: lgtm, approved, size/L

#1023 Add hh to Knative GitHub Org as a Member
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1022 Add hh@cncf.io to kn-infra-gcp-org-admins
  groups/groups_test.go
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1025 Add @cncf-ci to Knative Community
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1027 Add BobyMCbobs to knative and knative-sandbox orgs
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1029 Fixed links to Elekto
  elections/2022-TOC/README.md
  elections/2022-TOC/election_desc.md
Labels: lgtm, approved, size/XS

#1030 Add OWNERS file field to candidates template
  elections/2022-TOC/election.yaml
  elections/2022-TOC/nomination-template.md
Labels: lgtm, approved, size/XS
