Repository knative/community, pull requests merged in 2022-02, with the labels that each got.

#916 Add Murugappan to steering
  OWNERS_ALIASES
  STEERING-COMMITTEE.md
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M

#914 Add TOC to approvers for OWNERS_ALIASES
  OWNERS
Labels: lgtm, approved, size/S

#918 Update WORKING-GROUPS.md
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#911 remove myself from rabbitmq
  knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#922 update meeting notes link to point to the new document
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#919 🧹Update roadmap links as per process change
  mechanics/WORKING-GROUP-PROCESSES.md
  working-groups/docs/CHARTER.md
Labels: lgtm, approved, size/S, kind/documentation

#924 Lionel stepping down from Eventing Kafka WG
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS

#920 Adding mgencur to productivity reviewers
  OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, kind/enhancement

#926 Update EU seat
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS

#927 fix typo steering
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS

#928 Update OWNERS_ALIASES
  OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#929 GSOC 22 Idea: Improve Knative Eventing Observability
  google-summer-of-code/gsoc-2022.md
Labels: lgtm, approved, size/M

#931 Remove event-delivery WG from TOC.schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/XS

#930 Add Maximilien as the reviewer and writer of operator
  OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#905 Adopt K8s infra for gsuite mgmt
  groups/Makefile
  groups/OWNERS
  groups/README.md
  groups/client.go
  groups/committee-code-of-conduct/OWNERS
  groups/committee-code-of-conduct/groups.yaml
  groups/committee-oversight/OWNERS
  groups/committee-oversight/groups.yaml
  groups/committee-steering/OWNERS
  groups/committee-steering/groups.yaml
  groups/committee-trademark/OWNERS
  groups/committee-trademark/groups.yaml
  groups/config.yaml
  groups/fake/fake_client.go
  groups/go.mod
  groups/go.sum
  groups/groups.yaml
  groups/groups_test.go
  groups/reconcile.go
  groups/reconcile_test.go
  groups/restrictions.yaml
  groups/service.go
  groups/service_test.go
  groups/wg-productivity/OWNERS
  groups/wg-productivity/groups.yaml
  groups/wg-security/OWNERS
  groups/wg-security/groups.yaml
Labels: lgtm, approved, size/XXL
