Repository knative/community, pull requests merged in 2022-05, with the labels that each got.

#1037 Adding n3wscott to TOC paribolos files
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1041 feat(ADOPTERS.MD) Add ManoMano as adopter
  ADOPTERS.MD
Labels: lgtm, approved, size/XS, ok-to-test, kind/documentation

#1042 Adds HighCohesion details to Adopter doc
  ADOPTERS.MD
Labels: lgtm, approved, size/XS, ok-to-test, kind/documentation

#1048 chore: alphabetize ADOPTERS.md
  ADOPTERS.MD
Labels: lgtm, approved, size/XS

#1051 chore: add original boson contributors to knative
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1055 Add Paul to kperf approvers
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1054 Add dsimansk as 2022 TOC candidate
  elections/2022-TOC/candidate-dsimansk.md
Labels: lgtm, approved, size/S

#1035 Adding Scott as 2022 TOC candidate
  elections/2022-TOC/canidate-n3wscott.md
Labels: lgtm, approved, size/S

#1026 Add Paul as TOC candidate
  elections/2022-TOC/candidate-psschwei.md
Labels: lgtm, approved, size/S

#1036 Add dprotaso as 2022 TOC Candidate
  elections/2022-TOC/candidate-dprotaso.md
Labels: lgtm, approved, size/S

#1039 Adding skonto as 2022 TOC candidate
  elections/2022-TOC/candidate-skonto.md
Labels: lgtm, approved, size/S

#1053 Add Zbynek as TOC candidate
  elections/2022-TOC/candidate-zroubalik.md
Labels: lgtm, approved, size/S

#1056 Add msalatino (salaboy) as a TOC candidate
  elections/2022-TOC/candidate-msalatino.md
Labels: lgtm, approved, size/S

#1059 Fix name of Mauricio's candidate file so that it
  elections/2022-TOC/candidate-salaboy.md
Labels: lgtm, approved, size/XS

#1060 add myself as async-component approver
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1065 Update Paul's candidate profile
  elections/2022-TOC/candidate-psschwei.md
Labels: lgtm, approved, size/XS

#1066 Release 1.0 no longer supported
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS

#1047 allow emails for calendar-maintainers group
  groups/groups.yaml
Labels: lgtm, approved, size/S

#1067 [peribolos] Merge Scaling and Serving API Working Groups
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M

#1068 update serving and networking meeting details
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1073 adding exception to voters.yaml
  elections/2022-TOC/voters.yaml
Labels: lgtm, approved, size/XS

#1074 Add pierdipi to wg-leads
  groups/groups.yaml
Labels: lgtm, approved, size/XS

#1076 update TOC review schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/M

#1070 Remove zhiminxiang from networking WG lead
  groups/groups.yaml
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1080 chore: add functions to TOC review schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/M

#1081 After 1.5 release, 1.1 is no longer supported
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS
