Repository knative/community, pull requests merged in 2022-06, with the labels that each got.

#1078 Remove antoineco
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, kind/cleanup, kind/deprecation

#1058 add nader ziada as approver for sandbox/kperf
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1077 Add Carlisia as approver
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1075 Drop API core team from sandbox
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1085 Add @norbjd to sandbox members
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1071 Add GH Labels
  label_sync/OWNERS
  label_sync/labels.yaml
Labels: lgtm, approved, size/M

#1069 Proposing that SC, TOC, and Trademark Committee members should be eligible to vote.
  mechanics/SC.md
  mechanics/TOC.md
Labels: lgtm, approved, size/XS

#1089 Update release leads for v1.6
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1093 Add productivity wg leads as repo admins
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1095 Fix Error Wrapping Verb for go 1.18
  groups/reconcile_test.go
  groups/service_test.go
Labels: lgtm, approved, size/S, kind/cleanup

#1090 Update TOC members: add dsimansk and zroubalik
  groups/committee-oversight/groups.yaml
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1092 Nominate Ashleigh Brennan as DUX Working Group Lead
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1094 Nominate Mahamed Ali as Productivity WG Lead
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1097 Update productivity for knative-admins
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1098 shift WG updates by a week by request from DUX WG
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/M

#1032 Create a Functions WG
  working-groups/WORKING-GROUPS.md
  working-groups/functions/CHARTER.md
Labels: lgtm, approved, size/M

#1038 Proposed changes to Branding Guidelines for clarifications and conformance
  BRANDING.MD
Labels: lgtm, approved, size/S, kind/cleanup

#1101 Add new `admins@knative.dev` google group
  groups/groups.yaml
  groups/groups_test.go
  groups/restrictions.yaml
Labels: lgtm, approved, size/S

#1091 Add functions working group teams to peribolos
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1104 chizhg steps down from Productivity WG lead and leaves Knative
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1102 chore: change Google CLA to EasyCLA in contributing guide
  CONTRIBUTING.md
Labels: lgtm, approved, size/XS
