Repository knative/community, pull requests merged in 2023-02, with the labels that each got.

#1257 update release schedule and min k8s versions
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/S

#1255 Add Chainguard/puerco nomination for the EU seat
  elections/2022-SC-EU/candidate-puerco.md
Labels: lgtm, approved, size/S, needs-ok-to-test

#1254 Adds slack links to CNCF Knative slack channel
  google-summer-of-code/gsoc-2022.md
  google-summer-of-code/gsoc-2023.md
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/M, needs-ok-to-test

#1260 chore: update WG presentation schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/M

#1261 add serving review team to sandbox
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/validate-schema.py
Labels: lgtm, approved, size/XS

#1262 Update Serving Reviewers and drop in-active reviewers/members
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/L

#1264 Working at VMware and will contribute to Knative
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1266 add: jrangelramos to func-writer group
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1259 Add knative/.artifacthub repository
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1271 Fix permissions for .artifacthub repo
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1273 Revert "Add dave to privileged infra group"
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/XS

#1274 Fixing output if ./hack/update-codegen.sh doesn't update
  mechanics/tools/gen-aliases/main.go
Labels: lgtm, approved, size/XS, ok-to-test, kind/cleanup

#1275 re-add chzhyang to knative-snadbox/kperf approvers
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1272 remove inactive members from prod group
  groups/OWNERS
  groups/groups_test.go
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/M

#1277 update serving teams
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M

#1280 Update Slack link in new repo template
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: lgtm, approved, size/XS

#1279 Changing deprecated functions in ./hack/update-codegen.sh
  groups/reconcile.go
  mechanics/tools/gen-aliases/main.go
Labels: lgtm, approved, size/S, ok-to-test, kind/cleanup

#1269 Adding @puerco to streering mailing list
  groups/committee-steering/groups.yaml
Labels: lgtm, approved, size/XS, kind/enhancement

#1282 use OWNER aliases vs. specific people
  groups/OWNERS
  label_sync/OWNERS
Labels: lgtm, approved, size/XS

#1281 drop kind/good-first-issue label
  label_sync/labels.yaml
Labels: lgtm, approved, size/XS

#1283 fix dates so knative.party works
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/XS

#1284 docs: update STEERING-COMMITTEE.md with @puerco
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS

#1270 Adding @puerco to calendar maintainers
  groups/groups.yaml
Labels: lgtm, approved, size/XS, kind/enhancement

#1287 Allow release leads to submit jobs to prow via kubectl
  groups/OWNERS
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/S

#1292 update review schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S

#1289 drop google bots
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1294 :bug: Correct links in new-repo template
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: lgtm, approved, size/S, kind/bug
