Repository knative/community, pull requests merged in 2023-08, with the labels that each got.

#1411 HoldTillRename: Rename knative-sandbox to knative-extensions
  .github/ISSUE_TEMPLATE/new-repo.md
  .github/workflows/peribolos-schema-validate.yaml
  .github/workflows/verify.yaml
  REPOSITORY-GUIDELINES.md
  ROLES.md
  hack/update-codegen.sh
  mechanics/CREATING-A-SANDBOX-REPO.md
  mechanics/MATURITY-LEVELS.md
  mechanics/ROADMAPS.md
  mechanics/TOC.md
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: approved, do-not-merge/hold, size/M

#1412 Update name and description on knative-extensions
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/XS, kind/enhancement

#1408 Update Release Schedule (1.11)
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS

#1409 Update eventing-rabbitmq maintainers
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/S

#1410 Update Eventing description
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1414 Add creydr as eventing approver
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1395 Zbynek stepping down from TOC
  TECH-OVERSIGHT-COMMITTEE.md
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1406 Add Property.xyz to ADOPTERS.md
  ADOPTERS.MD
Labels: lgtm, approved, size/XS

#1413 Update function working group lead
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
  working-groups/functions/CHARTER.md
Labels: lgtm, approved, size/S

#1421 remove cncf-infra label
  label_sync/labels.yaml
Labels: lgtm, approved, size/XS

#1424 give retocode access to perf tests
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/S

#1423 Update knative-extensions.yaml
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/XS
