Repository knative/community, pull requests merged in 2023-01, with the labels that each got.

#1242 Remove albertomilan from knative groups
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1241 Remove albertomilan from knative groups
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1243 Add dave to privileged infra group
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/XS

#1236 Add myself to the community
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1244 Drop in-active members
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XL

#1245 Add knative-sandbox/eventing-istio
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/S

#1249 Add myself to net-kourier approver
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1250 Update TOC schedule for first part of 2023
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S

#1252 Remove GSoC ideas list, add GSoC guides
  google-summer-of-code/gsoc-2023.md
Labels: lgtm, approved, size/L
