Repository knative/community, pull requests merged in 2023-05, with the labels that each got.

#1332 DRAFT: Initial files for 2023 TOC Elections
  elections/2023-TOC/OWNERS
  elections/2023-TOC/README.md
  elections/2023-TOC/election.yaml
  elections/2023-TOC/election_desc.md
  elections/2023-TOC/nomination-template.md
  elections/2023-TOC/voters.yaml
  groups/committee-steering/groups.yaml
Labels: lgtm, approved, size/L

#1337 Fix broken links in 2023 TOC Election README
  elections/2023-TOC/README.md
Labels: lgtm, approved, size/XS

#1335 Merge eventing-kafka and eventing working groups
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/M

#1331 Removed references to CIVS
  elections/README.md
  mechanics/SC.md
Labels: lgtm, approved, size/XS

#1339 Add @pymhq as Member for Knative
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1340 Add @pymhq as Member for Knative Sandbox
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1341 Fix two broken links in ROLES.md
  ROLES.md
Labels: lgtm, approved, size/XS, ok-to-test

#1338 Add Gojek to list of Adopters
  ADOPTERS.MD
Labels: lgtm, approved, size/XS, ok-to-test

#1342 Add myself to community members
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1344 Add myself as TOC candidate
  elections/2023-TOC/candidate-kvmware.md
Labels: lgtm, approved, size/S

#1345 Create candidate-davidhadas.md
  elections/2023-TOC/candidate-davidhadas.md
Labels: lgtm, approved, size/M

#1353 update serving reviewers
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1352 drop archived repos and associated teams
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/M

#1363 Update TOC review schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/M

#1364 Add Cali0707 to knative and knative-sandbox
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1366 add Leo6Leo as member
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1365 Add myself to members in `knative.yaml` and `knative-sandbox.yaml`
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1362 Update meeting notes for productivity WORKING-GROUPS.md
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS
