Repository knative/community, pull requests merged in 2023-09, with the labels that each got.

#1426 Drop the go policy consistency clause
  mechanics/GOLANG-POLICY.md
Labels: lgtm, approved, size/XS

#1427 Add lkingland to WG leads and calendar maintainers
  groups/groups.yaml
Labels: lgtm, approved, size/XS

#1428 Added cali0707 as eventing reviewer
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1431 Align org admins of knative and knative-extensions
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/XS

#1430 Add David Hadas to TOC charter
  TECH-OVERSIGHT-COMMITTEE.md
  groups/committee-oversight/groups.yaml
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1433 archive knative-extensions/kperf
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1436 Add @yuzisun into the Knative community
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1437 Add @sukumargaonkar into Knative community
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1438 Update TOC review schedule due to skipped call
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S

#1435 Propose to create the new repo serving-progressive-rollout
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/S

#1439 Update new repo template
  .github/ISSUE_TEMPLATE/new-repo.md
Labels: lgtm, approved, size/S

#1432 Update UX WG status
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/M
