Repository knative/community, pull requests merged in 2023-06, with the labels that each got.

#1370 2023 TOC election results
  elections/2023-TOC/results.md
Labels: lgtm, approved, size/S

#1372 Add Krsna as owner to groups
  groups/committee-oversight/groups.yaml
  groups/groups.yaml
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/XS

#1368 chore: update TOC member status
  TECH-OVERSIGHT-COMMITTEE.md
Labels: lgtm, approved, size/XS

#1374 Allow anyone to send emails to `automation@knative.team`
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/XS

#1346 Update repo guidelines with CLOMonitor instructions
  .github/ISSUE_TEMPLATE/new-repo.md
  REPOSITORY-GUIDELINES.md
  mechanics/CREATING-A-SANDBOX-REPO.md
Labels: lgtm, approved, size/M

#1376 Add Y Meadows to ADOPTERS.MD
  ADOPTERS.MD
Labels: lgtm, approved, size/XS, ok-to-test

#1381 Add issue form for ADOPTERS.yaml
  .github/ISSUE_TEMPLATE/ADOPTERS.yaml
Labels: lgtm, approved, size/M

#1382 updated my email address with my personal one, since I'm leaving VMwa…
  groups/committee-steering/groups.yaml
Labels: lgtm, approved, size/XS

#1386 Update toc review schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/XS

#1387 Update leads for 1.11
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1343 update ROLES.md to more accurately reflect reality
  ROLES.md
Labels: lgtm, approved, size/L
