Repository knative/community, pull requests merged in 2023-07, with the labels that each got.

#1388 chore: add Sonavi Labs to ADOPTERS.MD
  ADOPTERS.MD
Labels: lgtm, approved, size/XS

#1393 Remove gab-satchi from owners
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS

#1394 Paul stepping down as Serving WG Lead
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1385 Hand off VMware trademark seat to Sameer
  TRADEMARK-COMMITTEE.md
  groups/committee-trademark/groups.yaml
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1396 adding skonto, nak3 and retocode as docs reviewers+writers
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1397 adding dan-j as knative-sandbox member
  peribolos/knative-sandbox.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1402 No quorum for 7/20 TOC call
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S

#1404 Update my Company affiliation
  groups/groups_test.go
  groups/wg-productivity/groups.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS

#1405 gauron99 func reviewer
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS
