Repository knative/community, pull requests merged in 2023-11, with the labels that each got.

#1459 Update TOC review schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/M

#1461 Update DUX references to UX references on TOC review schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/XS

#1464 New repo: Add backstage-plugins repository
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/S

#1467 2023 SC election results
  elections/2023-SC/results.md
Labels: lgtm, approved, size/S

#1465 Add cali0707 as eventing approver
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1462 Update support window mentioned in the MATURITY-LEVELS.md
  mechanics/MATURITY-LEVELS.md
Labels: lgtm, approved, size/XS

#1471 Add @alexagriffith into the Knative community
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1470 Company change update
  TECH-OVERSIGHT-COMMITTEE.md
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/M

#1469 Update SC members and SC permissions
  STEERING-COMMITTEE.md
  groups/committee-steering/groups.yaml
  groups/groups.yaml
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/L
