Repository knative/community, pull requests merged in 2023-04, with the labels that each got.

#1319 Add `dsimansk` and `zroubalik` to admin group
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1320 Update Eventing WG meeting time
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS, kind/documentation

#1321 Grant @jeefy GCP admin access
  groups/groups_test.go
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/XS

#1323 drop actions-downstream-test
  peribolos/knative-sandbox.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1324 Update 1.10 Release Leads
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1326 Ashleigh stepping down as Docs WG lead
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S, kind/removal

#1327 Update TOC review schedule to every other week
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S

#1328 adding vishal-chdhry-to-members
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1333 Propose David Hadas as a security WG lead
  groups/wg-security/groups.yaml
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS

#1334 Add Stavros as Serving approver
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-sandbox-OWNERS_ALIASES
  peribolos/knative-sandbox.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS
