Repository knative/community, pull requests merged in 2024-03, with the labels that each got.

#1524 New private Google group for UX WG leads
  groups/restrictions.yaml
  groups/wg-ux/OWNERS
  groups/wg-ux/groups.yaml
Labels: lgtm, approved, size/S

#1521 Add nrrso to SC
  STEERING-COMMITTEE.md
  groups/committee-steering/groups.yaml
  groups/groups.yaml
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M

#1508 Add definitions of alpha/beta/GA to maturity levels
  mechanics/MATURITY-LEVELS.md
Labels: lgtm, approved, size/M

#1533 remove nrrso until he accepts GitHub org invites
  peribolos/active-users
  peribolos/inactive-users.py
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XXL

#1532 Add Iliia Khaprov @ RabbitMQ as Eventing RabbitMQ maintainer
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test, kind/enhancement

#1534 Add folks from RabbitMQ Team
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1535 Add Michal Kuratczyk and Aitor Pérez Cedres from RabbitMQ Team to Evenitng RabbitMQ
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/XS

#1536 Request from Ali Ok to remove eric-sap and travis-minke-sap
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/S, ok-to-test

#1538 Drop some rabbitmq integration maintainers
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/XS

#1539 Update knative-extensions.yaml
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/XS

#1543 Remove vaibhavjainwiz and spolti as the approvers for Eventing Kogito
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/XS

#1546 Add Kuack to the README
  README.md
  mascot/kuack.png
Labels: lgtm, approved, size/XS

#1547 Remove emeritus WGs from Peribolos
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M
