Repository knative/community, pull requests merged in 2024-09, with the labels that each got.

#1609 swap out krsna for dave in productivity google group
  groups/groups_test.go
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/XS

#1610 Remove some inactive folks from Peribolos
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1587 Combine Steering and TO Committees
  GOVERNANCE.md
  STEERING-COMMITTEE.md
  TECH-OVERSIGHT-COMMITTEE.md
Labels: lgtm, approved, size/L

#1614 Revert ":robot: Adding entries for eventing-integrations (#1612)"
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/S

#1615 Remove 'shinigambit' user from peribolos configs
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1616 Remove 'thisisnotapril' user from knative-extensions config
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/XS

#1617 :robot: Adding entries for eventing-integrations
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/S
