Repository knative/community, pull requests merged in 2024-02, with the labels that each got.

#1501 Updated 2023-SC-EU folder and contents to 2024-SC-EU
  elections/2024-SC-EU/README.md
  elections/2024-SC-EU/nomination-template.md
Labels: lgtm, approved, size/XS, needs-ok-to-test, kind/documentation

#1497 Delete working-groups/security/vmt.rotation
  working-groups/security/vmt.rotation
Labels: lgtm, approved, size/S

#1504 Add SVA/nrrso nomination for the EU seat
  elections/2023-SC-EU/candidate-nrrso.md
Labels: lgtm, approved, size/S, ok-to-test

#1506 TM committee dissolving
  BRANDING.MD
  CALENDAR.MD
  GOVERNANCE.md
  README.md
  REPOSITORY-GUIDELINES.md
  STEERING-COMMITTEE.md
  TECH-OVERSIGHT-COMMITTEE.md
  TRADEMARK-COMMITTEE.md
  groups/committee-trademark/OWNERS
  groups/committee-trademark/groups.yaml
  groups/restrictions.yaml
  mechanics/GDRIVE.md
  mechanics/SC.md
  mechanics/TOC.md
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/L

#1510 add izabelacg to the team that can triage issues and as a serving reviewer
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1509 docs: add john vanzuita to org
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1511 Drop inactive Broadcom Serving reviewers
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1512 Move SC EU candidate file to correct directory
  elections/2024-SC-EU/candidate-nrrso.md
Labels: lgtm, approved, size/XS

#1513 Add SVA to adopters list
  ADOPTERS.MD
Labels: lgtm, approved, size/M

#1516 Include knative.dev/pkg in the list of serving repos
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS

#1517 Adding myself as member of func-writers
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1519 membership: add sadath-12
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1522 Use slack ids rather than handles for toc review notifications
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S
