Repository knative/community, pull requests merged in 2024-04, with the labels that each got.

#1550 update release leads for 1.14
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1552 Step down as client approver
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1556 Promote cardil to admin temporarily to transfer issues
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1557 Revert "Promote cardil to admin temporarily to transfer issues"
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1559 Add ReToCode as serving approver
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1565 func-python: adds knative-extensions/func-python
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/S, kind/enhancement

#1564 Archive knative-extensions/net-certmanager repository
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/S

#1566 Adding matzew for Knative Function
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/XS
