Repository knative/community, pull requests merged in 2024-01, with the labels that each got.

#1480 Add Leo Li as release lead for 1.13
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1483 Move TOC meetings to wednesdays
  TECH-OVERSIGHT-COMMITTEE.md
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/M

#1484 Drop VMware folks from approver/reviewer roles who are no longer active
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1476 Drop emeritus leads from various group
  groups/committee-oversight/groups.yaml
  groups/groups.yaml
Labels: lgtm, approved, size/M

#1485 Fix typo in GitHub Action
  .github/workflows/peribolos-schema-validate.yaml
Labels: lgtm, approved, size/XS

#1486 Chainguard taking ownership of eventing-rabbitmq
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/S

#1481 Update min K8s versions in our release schedule
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS

#1488 add xiangpingjiang to knative and knative-extensions
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1489 Create folder and files for 2023-2024 end user seat
  elections/2023-SC-EU/README.md
  elections/2023-SC-EU/nomination-template.md
Labels: lgtm, approved, size/M

#1490 Update README.md- make the end date floating
  elections/2023-SC-EU/README.md
Labels: lgtm, approved, size/XS

#1491 add cmurray as wg lead to working group leads list
  groups/groups.yaml
Labels: lgtm, approved, size/XS

#1492 drop juan from serving reviewers
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1474 change gauron99 to FuncWriters
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1494 Update release schedule
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS

#1496 Update TOC-REVIEW.schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S

#1495 minor typo
  CODE-OF-CONDUCT.md
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1498 Drop myself from members
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S
