Repository knative/community, pull requests merged in 2024-11, with the labels that each got.

#1626 Revoke Release Leads role after 1.16 release
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1631 Fix devstats link
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS

#1632 Fix SC voter eligibility
  STEERING-COMMITTEE.md
Labels: lgtm, approved, size/XS

#1629 2024 SC Election Files
  elections/2024-SC/OWNERS
  elections/2024-SC/README.md
  elections/2024-SC/election.yaml
  elections/2024-SC/nomination-template.md
  elections/2024-SC/voters.yaml
Labels: lgtm, approved, size/L

#1633 Add Alauda as an adopter
  ADOPTERS.MD
Labels: lgtm, approved, size/XS

#1634 Adopters - Drop TriggerMesh, update VMware Product Name
  ADOPTERS.MD
Labels: lgtm, approved, size/XS

#1635 Add Cisco as an adopter
  ADOPTERS.MD
Labels: lgtm, approved, size/XS

#1636 Add Daniel Krook(CNCF) and Mario Fahlandt(Kubermatic) to GCP for Spen…
  groups/groups_test.go
  groups/wg-productivity/groups.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1637 add Hadrian as an ADOPTER
  ADOPTERS.MD
Labels: lgtm, approved, size/XS

#1638 Drop/update ADOPTERS who's links don't work
  ADOPTERS.MD
Labels: lgtm, approved, size/XS

#1639 drop HighCohesion as an adopter
  ADOPTERS.MD
Labels: lgtm, approved, size/XS

#1640 SC Election: Adding nomination
  elections/2024-SC/candidate-matzew.md
Labels: lgtm, approved, size/S

#1641 Add KSC members to peribolos toc alias temporarily
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M

#1642 Update ADOPTERS.MD
  ADOPTERS.MD
Labels: lgtm, approved, size/XS, ok-to-test

#1643 Remove owners field in 2024 SC election config
  elections/2024-SC/election.yaml
Labels: lgtm, approved, size/XS

#1644 Nominate dprotaso for SC 2024 election
  elections/2024-SC/candidate-dprotaso.md
Labels: lgtm, approved, size/S
