Repository knative/community, pull requests merged in 2024-07, with the labels that each got.

#1588 skip july 3rd toc meeting
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S

#1589 Add rahulii as knative member
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1590 Add release leads rotation for Knative v1.15
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M

#1591 Archive plugin repositories without releases and current maintenainers
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/S

#1577 Update WG leads group
  groups/groups.yaml
Labels: lgtm, approved, size/M

#1586 adding ShravaniAK as community member
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, ok-to-test

#1593 Update toc review schedule
  mechanics/TOC-REVIEW.schedule
Labels: lgtm, approved, size/S

#1594 Updated the Serving WG meeting time
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/S

#1596 Update release schedule
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS

#1597 Revoke Release Leads role for completed release
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/M
