Repository knative/community, pull requests merged in 2025-01, with the labels that each got.

#1656 Update release leads for Knative 1.17
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1657 Update committee membership
  STEERING-COMMITTEE.md
  groups/committee-code-of-conduct/OWNERS
  groups/committee-code-of-conduct/groups.yaml
  groups/committee-steering/groups.yaml
  groups/groups.yaml
  groups/restrictions.yaml
  groups/wg-productivity/groups.yaml
  groups/wg-security/groups.yaml
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/L

#1658 drop izabela as a reviewer
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1659 fix peribolos and google groups config
  groups/groups.yaml
  groups/wg-productivity/groups.yaml
  groups/wg-security/groups.yaml
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/L

#1661 adjust memberships
  groups/groups.yaml
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/S

#1662 Fix calendar group
  groups/groups.yaml
Labels: lgtm, approved, size/M

#1663 Updating golang tools to latest versions
  .github/workflows/verify.yaml
  groups/go.mod
  groups/go.sum
  groups/reconcile.go
  mechanics/tools/gen-aliases/go.mod
  mechanics/tools/gen-aliases/go.sum
Labels: lgtm, approved, size/XXL

#1665 paul stepping down as extensions approver
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
Labels: lgtm, approved, size/XS

#1664 Update release schedule for next cycle
  mechanics/RELEASE-SCHEDULE.md
Labels: lgtm, approved, size/XS
