Repository knative/community, pull requests merged in 2025-02, with the labels that each got.

#1660 2025 SC EU seat elections
  elections/2025-SC-EU/README.md
  elections/2025-SC-EU/nomination-template.md
Labels: lgtm, approved, size/M

#1671 Add dsimansk to Serving approvers
  peribolos/knative-OWNERS_ALIASES
  peribolos/knative-extensions-OWNERS_ALIASES
  peribolos/knative-extensions.yaml
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS

#1667 Add KA-NABELL/kahirokunn nomination for the EU seat
  elections/2025-SC-EU/candidate-kahirokunn.md
Labels: lgtm, approved, size/S

#1668 Nominate arsenetar for the 2025 SC EU
  ADOPTERS.MD
  elections/2025-SC-EU/candidate-arsenetar.md
Labels: lgtm, approved, size/M, ok-to-test

#1669 Add Judson Lester (nyarly) as 2025 End User candidate
  elections/2025-SC-EU/candidate-nyarly.md
Labels: lgtm, approved, size/S, ok-to-test
