Repository knative/community, pull requests merged in 2025-05, with the labels that each got.

#1684 Add Fedosin to the list of members
  peribolos/knative.yaml
Labels: lgtm, approved, size/XS, needs-ok-to-test

#1685 Re-add GOVERNANCE.md removed in #1587, and add MAINTAINERS.md
  GOVERNANCE.md
  MAINTAINERS.md
  ROLES.md
Labels: lgtm, approved, size/M, kind/documentation

#1689 Update roadmap links for serving, UX
  working-groups/WORKING-GROUPS.md
Labels: lgtm, approved, size/XS
